export interface FlashCard {
  letter: string;
  word: string;
  image: string;
   // Optional for English and Arabic cards, but included for consistency
}

export const ENGLISH_FLASH_CARDS: FlashCard[] = [
  { letter: 'A', word: 'Apple', image: '🍎' },
  { letter: 'B', word: 'Ball', image: '⚽' },
  { letter: 'C', word: 'Cat', image: '🐱' },
  { letter: 'D', word: 'Dog', image: '🐶' },
  { letter: 'E', word: 'Elephant', image: '🐘' },
  { letter: 'F', word: 'Fish', image: '🐟' },
  { letter: 'G', word: 'Giraffe', image: '🦒' },
  { letter: 'H', word: 'Hat', image: '🎩' },
  { letter: 'I', word: 'Ice Cream', image: '🍦' },
  { letter: 'J', word: 'Juice', image: '🧃' },
  { letter: 'K', word: 'Kite', image: '🪁' },
  { letter: 'L', word: 'Lion', image: '🦁' },
  { letter: 'M', word: 'Monkey', image: '🐵' },
  { letter: 'N', word: 'Nest', image: '🪺' },
  { letter: 'O', word: 'Orange', image: '🍊' },
  { letter: 'P', word: 'Penguin', image: '🐧' },
  { letter: 'Q', word: 'Queen', image: '👸' },
  { letter: 'R', word: 'Rabbit', image: '🐰' },
  { letter: 'S', word: 'Sun', image: '☀️' },
  { letter: 'T', word: 'Tiger', image: '🐯' },
  { letter: 'U', word: 'Umbrella', image: '☂️' },
  { letter: 'V', word: 'Violin', image: '🎻' },
  { letter: 'W', word: 'Whale', image: '🐳' },
  { letter: 'X', word: 'Xylophone', image: '🎶' },
  { letter: 'Y', word: 'Yacht', image: '🛥️' },
  { letter: 'Z', word: 'Zebra', image: '🦓' },
];

export const ARABIC_FLASH_CARDS: FlashCard[] = [
  { letter: 'ا', word: 'أرنب', image: '🐇' },
  { letter: 'ب', word: 'بطة', image: '🦆' },
  { letter: 'ت', word: 'تفاح', image: '🍏' },
  { letter: 'ث', word: 'ثعلب', image: '🦊' },
  { letter: 'ج', word: 'جمل', image: '🐫' },
  { letter: 'ح', word: 'حصان', image: '🐎' },
  { letter: 'خ', word: 'خروف', image: '🐑' },
  { letter: 'د', word: 'ديك', image: '🐓' },
  { letter: 'ذ', word: 'ذئب', image: '🐺' },
  { letter: 'ر', word: 'رمان', image: '🍎' },
  { letter: 'ز', word: 'زرافة', image: '🦒' },
  { letter: 'س', word: 'سمكة', image: '🐟' },
  { letter: 'ش', word: 'شمس', image: '☀️' },
  { letter: 'ص', word: 'صقر', image: '🦅' },
  { letter: 'ض', word: 'ضفدع', image: '🐸' },
  { letter: 'ط', word: 'طاووس', image: '🦚' },
  { letter: 'ظ', word: 'ظبي', image: '🦌' },
  { letter: 'ع', word: 'عصفور', image: '🐦' },
  { letter: 'غ', word: 'غزال', image: '🦌' },
  { letter: 'ف', word: 'فيل', image: '🐘' },
  { letter: 'ق', word: 'قرد', image: '🐒' },
  { letter: 'ك', word: 'كلب', image: '🐶' },
  { letter: 'ل', word: 'لبن', image: '🥛' },
  { letter: 'م', word: 'موز', image: '🍌' },
  { letter: 'ن', word: 'نمر', image: '🐅' },
  { letter: 'هـ', word: 'هدهد', image: '🦉' },
  { letter: 'و', word: 'وردة', image: '🌹' },
  { letter: 'ي', word: 'يمامة', image: '🕊️' },
];

export const NUMBER_FLASH_CARDS: FlashCard[] = [
  { letter: '1', word: 'One Apple', image: '🍎' },
  { letter: '2', word: 'Two Bananas', image: '🍌🍌' },
  { letter: '3', word: 'Three Cherries', image: '🍒🍒🍒' },
  { letter: '4', word: 'Four Strawberries', image: '🍓🍓🍓🍓' },
  { letter: '5', word: 'Five Lemons', image: '🍋🍋🍋🍋🍋' },
  { letter: '6', word: 'Six Grapes', image: '🍇🍇🍇🍇🍇🍇' },
  { letter: '7', word: 'Seven Oranges', image: '🍊🍊🍊🍊🍊🍊🍊' },
  { letter: '8', word: 'Eight Watermelons', image: '🍉🍉🍉🍉🍉🍉🍉🍉' },
  { letter: '9', word: 'Nine Peaches', image: '🍑🍑🍑🍑🍑🍑🍑🍑🍑' },
  { letter: '10', word: 'Ten Apples', image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎' },
  { letter: '11', word: 'Eleven Bananas', image: '🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌' },
  { letter: '12', word: 'Twelve Cherries', image: '🍒🍒🍒🍒🍒🍒🍒🍒🍒🍒🍒🍒' },
  { letter: '13', word: 'Thirteen Strawberries', image: '🍓🍓🍓🍓🍓🍓🍓🍓🍓🍓🍓🍓🍓' },
  { letter: '14', word: 'Fourteen Lemons', image: '🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋' },
  { letter: '15', word: 'Fifteen Grapes', image: '🍇🍇🍇🍇🍇🍇🍇🍇🍇🍇🍇🍇🍇🍇🍇' },
  { letter: '16', word: 'Sixteen Oranges', image: '🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊' },
  { letter: '17', word: 'Seventeen Watermelons', image: '🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉' },
  { letter: '18', word: 'Eighteen Peaches', image: '🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑' },
  { letter: '19', word: 'Nineteen Apples', image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎' },
  { letter: '20', word: 'Twenty Bananas', image: '🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌' },
];
